language: java
sudo: false # faster builds

jdk:
  - openjdk11
  - oraclejdk11
  - openjdk8
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle

install: true

script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
  - travis_wait 30 ./gradlew clean build -x test
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - if [ -f turbo.log ]; then echo "------TAIL of turbo.log------"; tail -n 1000 turbo.log; echo "------END of turbo.log------"; fi
